### ISSUE TITLE
Missing Contig1 file during analyis of some sequences

### ISSUE THREAD

**Issue by JFWolters** [BFL-lab/Mfannot#15]
Hello,

I am currently having a lot more success with MFANNOT thanks to your prior help but Ive run into an odd intermittent issue. 

Occasionally, some of the sequences in a large collection I am working on fail to be annotated, even though several sequences from the same set are annotated with no issue.

Using just one as an example, it failed with the error:
No contig found for contig1_1334 [74205 - 76691] in /home/GLBRCORG/jwolters/packages/Mfannot-master/examples/mfannot_test_10102018/contig/contig1//contig1.orf

The file path in the error message looks odd as it contains a double slash after contig1

One thing to note is that my system does not seem to recognize that the file Contig/contig1 actually exists and I receive an error message while trying to copy it to my local system from the server I am working on.

However, I can still open the file on the server and it appears normal there

I received this error while running it for debugging purposes using the command:
mfannot -g 3 --d --T ~/packages/Mfannot-master/examples/mfannot_test_10102018 flattened_line_58.fasta >& mfannot_log

I have attached that test folder which includes the problematic sequence. Im not sure yet if this error is the reason all of them are failing but I will be looking into that in more detail later.
[mfannot_test_10102018.zip](https://github.com/BFL-lab/Mfannot/files/2466133/mfannot_test_10102018.zip)

**Comment by natacha-beck** [comment]
@JFWolters , I did not get the chance to take a look to your issue. I will try to do that in the next couple of days. And will let you know what I will found. I suspect something in the installation, since the docker image seems to work properly. 

Natacha

**Comment by natacha-beck** [comment]
@JFWolters Once again sorry for the delay. After a look I suspect that you did not install grab-fasta and grab-seq ([here](https://github.com/BFL-lab/grab-fasta)). Can you take a look. Once you have this one installed you can try the following to test it: 

In `contig/contig1` run this:

> contig/contig1# grab-fasta -f contig1.orf -H contig1.list -o - 

You should get the following: 

> >contig1_1334 [74205 - 76691] 
> VSHITYTVFERNPFPISTCTMVHISRMTAYSKDDVRKMLTITKEFVTVYKDNKVTINYQS
> RPVVTFFTTTIGTFGISTFFTLRSLTNAWNEHRAKENSRRPMTTRQSSTMSKNGSREMYV
> PTGKTTTTRVIMPKPNRDRYAADKYLYKNFHTEQKVKTQKDMLNSKFTNQIVIMWRITIP
> RFYSKNTSLTFSQCFFTVTRTWTSTMIAKTDGQIVKNTISANGRKFARDLMYWMLIAFPA
> SYTNAAIKYLTNRLSTGFRTNLIRYIHDMYLDQVMTYYKVTLNTADIENIDQYITNDVTK
> FCDSICGLFSSMGKPFMDLVFFSVYLRDTLGTGAIVGIFANYFTTACVLKSFTPSFGKLS
> SQRTHTEGAYYNQHLNTITNSEEVAFYKGSKIEKEKLRETFDGTMNHVSNEINMSSMYSA
> LEDYVTKYTWSAWGYVFAGLPVFLEDLWPSSSTEHVDEGEAPPAPQTKKYVDENQNMRQF
> IMNKRLLTSLADAGSRLMYSIKDISDTTGYTDRVFTTTTNLHMTHAPAYSYRSKYGPSDI
> HGTVQKNYTGGVRFENIPVIIPSKDGSDGDILIDKTNFKTTNKHSTLILGSNGCGKTSIG
> RMMAGLWPLYYGLLSKPSDDDIFYLPQKTYFTNGNLRDQIMYPYSYDEMVARGYNDDHLY
> HMTREVKTDYLTTREGNFNVKKDWKDVFSGGEKQRMSIARVTFKKPKFVVLDESTNAVST
> DVEDYTFETLQKKNIAFITFSHRPLLMKYHDYVTEMKGGRKKGGWVFHDLTSEDNLKTID
> NEINEIESKTARIEEWEKRIDEIEKYTDGHNDDIKESAMDLEESISFEV

**Comment by JFWolters** [comment]
Hello,

You were totally correct, I installed grab-seq and grab-fasta and got exactly the expected result from running that command, and further, I ran mfannot on the problematic sequence and now it completed with no error. I'm sorry I had missed these needed tools, I don't recall seeing them in the README for MFANNOT.

Thank you again for all your help.

**Comment by natacha-beck** [comment]
It was missing, I just add the information in the readme. Thanks for all it help me to improve the documentation, sorry for this missing part

**Comment by JFWolters** [comment]
No worries, thank you again for all your help.
