### ISSUE TITLE
Failure during Intron/Exon Annotation

### ISSUE THREAD

**Issue by JFWolters** [BFL-lab/Mfannot#17]
Hello,

I have run into an issue where a file expected during execution of exonerate is missing.

The error comes up as "Can't read from '/tmp/mfannot.29578/Exonerate/out_nad1_e1': No such file or directory"

This only occurs on a very small subset of my data, and several files with annotated exons/introns work fine with no issues.

I have run a test and attached the results.

I ran the following command to generate the test output:
mfannot --d --T ~/packages/Mfannot-master/examples/mfannot_test_12172018 flattened_line_44.fasta >& mfannot_log
(I should have added -g 3 but the error occurs regardless of translation table used).

Thank you again for all your prior help in debugging my various issues.

Best,
John Wolters
[mfannot_test_12172018.zip](https://github.com/BFL-lab/Mfannot/files/2687821/mfannot_test_12172018.zip)

**Comment by natacha-beck** [comment]
Hi John, 

Are you sure to use the latest version of MFannot ?

The issue seems to be the one I have fixed here: 

https://github.com/BFL-lab/Mfannot/pull/14/commits/a9cef99c5661e8223ddd394d356bf543aeffe405 

Can you verify that you used the latest version.

**Comment by JFWolters** [comment]
Hello,

You are correct, I was using version 1.34 and after updating to 1.35 I no longer have this issue. Thats what I get for not checking for updates first.

Thank you again for your help.
