### ISSUE TITLE
Any plans for a Singularity or conda package? [Not a real issue]

### ISSUE THREAD

**Issue by PerisD** [BFL-lab/Mfannot#40]
Dear MFannot developers,
The program is awesome and I use it via webserver several times. Are you planning to develop a conda or singularity package, integrating everything. I found quite difficult to install all dependencies and perl modules requested by the MFannot.
Thanks for your efforts!
Peris

**Comment by cgjosephlee** [comment]
Maybe this https://github.com/BFL-lab/Mfannot/issues/16#issuecomment-488812897 ?

**Comment by natacha-beck** [comment]
Oups for sure this: https://singularity-hub.org/collections/1608

**Comment by natacha-beck** [comment]
@PerisD You can have a look to the new images (docker) https://hub.docker.com/repository/docker/nbeck/mfannot

**Comment by PerisD** [comment]
Thanks a lot!
