### ISSUE TITLE
Sequin file missing a gene predicted in the .new file

### ISSUE THREAD

**Issue by MitosChondros** [BFL-lab/Mfannot#47]
Hello,

I am trying to annotate several mitochondrial genomes and I have noticed that in some cases, mfannot predicts genes (seemingly accurately) in the .new file, but there is no corresponding entry in the sequin file, so my final mitochondrial genome map is missing genes. It's not completely clear why this is happening, but it seems that it may happen in some cases where mfannot is not completely sure of where the start of the 'missing' gene is (e.g., starts inferred by similarity).

Is this a known issue, and if so, is there an easy way around it?

Thanks!

**Comment by natacha-beck** [comment]
Hello, 

Indeed your observation is right, but it is not a bug. MFannot put only the gene identified `perfectly` in the sqn file. We do not want people to directly submit the sqn file.

MFannot as you saud `predicts genes (seemingly accurately)` we want people to double check the result and validate the *sqn file. 

Best
