### ISSUE TITLE
Difficulty setting up MFANNOT: "No directory was found for blast"

### ISSUE THREAD

**Issue by JFWolters** [BFL-lab/Mfannot#5]
Hello,

I have been a user of the MFANNOT web interface for years and it has proven immensely useful in my past research.

I am interested in setting up MFANNOT on my own system but am having some difficulties specifically with getting it up and running.

Whenever I run mfannot, I get the following error:  "No directory was found for blast"

I have installed all dependencies and made sure all relevant files are accessible via the PATH, PERL5LIB, or   MF2SQN_LIB variables. All the binaries for the blast programs are in my path, though I do not know why the error message refers to a directory.

Regardless of how I run the program for debugging purposes, e.g. "mfannot -h", "mfannot -d" or "mfannot -l log_file", I get the same error and no debug or log file is generated. If I run "mfannot allomyces.fna" in the examples folder I get the same error.

I cannot find the line that generates this error message in mfannot, flip, the HMMsearch programs, mf2sqn, qualifs.pl, RNAfinder, or umac. 

Do you have any advice on what is generating this error and how I could correct it?

**Comment by JFWolters** [comment]
The issue was due to my error. I had not installed the required Static Data. Installing and setting the appropriate variables resolved this particular error.

**Comment by natacha-beck** [comment]
Hello, 

Thanks for the comment. I am glad that you were happy with MFannot online. 

Regarding the installation, you can use the docker image of [MFannot](https://hub.docker.com/r/nbeck/mfannot/) or the [Singularity](https://www.singularity-hub.org/collections/867) image. 

I will answer on the other issue to try to get you a valid installation. 
Natacha
